# Jekyll configuration

name: tangni
description: Software Developer

# Url is currently only used only for the RSS feed in feed.xml
#url: http://tonygao.cn
#url: http://localhost:4000
url: http://tangni.me

encoding: UTF-8

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: ''

social:
  github:
    id: t-gao
    name: t-gao
  stackoverflow:
    id: 1438744/t-gao
    name: t-gao
  googleplus:
    id: 108067432863444475775
    name: Jian Gao
  linkedin:
    id: AAIAAArE3BgB-mWcuAoiROhxznEomMwo8Rbj3es
    name: tony gao
  #rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrika (https://metrica.yandex.com/) leave blanc to ignore or put true to use
yandex_metrika:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: tangni
comments: true

permalink: /:year/:month/:title
paginate: 3

highlighter: rouge
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']

collections:
  my_tags:
    output: true
    permalink: /blog/tag/:name/